replicaCount: 2
image:
  repository: kirandevtn/wavy
  tag: "1.0"
  pullPolicy: IfNotPresent
service:
  name: wavy-service
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30100

env:
  - name: SESSION_SECRET
    value: "Kiran"
  - name: KEY
    value: "lkjhgfdsasdf"
  - name: ALGORITHM
    value: "aes-256-cbc"
  - name: MONGO_URL
    value: "mongodb://mongo-service:27017/wave?retryWrites=true&w=majority"
